descriptions:
  human: "&aHealth Boost 2"
  elf: "&aRegeneration 1 "
  orc: "&aStrength 0"
  beastfolk: "&aSpeed 1"
  dwarf: "&aHaste 1"
messages:
  assigned: "Race successfully assigned to %race%. Keep in mind that you can change your race again just ONE more time!"
  playerInfo: "&aYou current race is %race%"
  playerInfoNone: "&cYou currently don't have any race assigned!"
  specifyAssign: "&cSpecify a race to assign yourself"
  raceAlreadyAssigned: "&cYou already have a race assigned. Try /race change <race>"
  invalidRace: "&cSpecify a valid race!"
  argsErrorInfo: "&cNot enough args or too many args. Usage: /race info <race>"
  argsErrorChange: "&cNot enough args or too many args. Usage: /race change <race>"
  alreadyChanged: "&cI'm sorry, but you already changed your race 1 time"
  changed: "&aRace changed to %race%. You won't be able to change your race anymore."
  sameRacesChange: "&cYour old race and the new one you are trying to assign are the same."
  cannotChangeNotAssigned: "&cYou cannot change your race if you previously did not specify one"